# Generated by Django 3.2.11 on 2022-05-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FootballBookmaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField(max_length=11)),
                ('name', models.CharField(max_length=255, null=True)),
                ('url', models.CharField(max_length=255, null=True)),
                ('img', models.FileField(null=True, upload_to='bookmakers')),
            ],
        ),
        migrations.CreateModel(
            name='FootballMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(max_length=11)),
                ('match_date', models.CharField(max_length=250, null=True)),
                ('match_time', models.CharField(max_length=250, null=True)),
                ('match_url', models.CharField(max_length=250, null=True)),
                ('game', models.CharField(max_length=250, null=True)),
                ('league', models.CharField(max_length=250, null=True)),
                ('league_url', models.CharField(max_length=250, null=True)),
                ('league_img', models.FileField(null=True, upload_to='')),
                ('channel_img', models.FileField(null=True, upload_to='channels')),
                ('channel_title', models.CharField(max_length=250, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=100)),
                ('source_url', models.CharField(max_length=255)),
                ('status', models.SmallIntegerField(default=1, max_length=2)),
            ],
        ),
    ]
