# Generated by Django 3.2.11 on 2022-05-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballmatch',
            name='parsed_match_date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
