# Generated by Django 3.2.11 on 2022-05-28 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_auto_20220528_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballbookmaker',
            name='match_id',
        ),
        migrations.AddField(
            model_name='footballbookmaker',
            name='match',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, to='sports.footballmatch'),
            preserve_default=False,
        ),
    ]
