# Generated by Django 3.2.11 on 2022-05-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0004_auto_20220528_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballmatch',
            name='league_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='match_league_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='match_unique_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
