# Generated by Django 3.2.11 on 2022-05-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0005_auto_20220530_1540'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='footballmatch',
            index=models.Index(fields=['match_unique_id'], name='match_unique_id'),
        ),
        migrations.AddIndex(
            model_name='footballmatch',
            index=models.Index(fields=['parsed_match_date_time'], name='parsed_match_date_time'),
        ),
    ]
