# Generated by Django 3.2.11 on 2022-06-17 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0006_auto_20220530_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootballTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_unique_id', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('img', models.CharField(max_length=250, null=True)),
                ('land', models.CharField(max_length=250, null=True)),
                ('stadium', models.CharField(max_length=250, null=True)),
                ('location', models.CharField(max_length=250, null=True)),
                ('lat_lan', models.CharField(max_length=255, null=True)),
                ('capacity', models.CharField(max_length=250, null=True)),
                ('coach', models.CharField(max_length=250, null=True)),
                ('tournament_history', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='land',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='odds',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='prev_match',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='round',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='stadium',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='team_1_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='team_2_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='footballbookmaker',
            name='match',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='bookmakers', to='sports.footballmatch'),
        ),
    ]
