# Generated by Django 3.2.11 on 2022-06-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0007_auto_20220617_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballteam',
            name='team_unique_id',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
