# Generated by Django 3.2.11 on 2022-06-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0008_alter_footballteam_team_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballmatch',
            name='land',
        ),
        migrations.RemoveField(
            model_name='footballmatch',
            name='round',
        ),
        migrations.RemoveField(
            model_name='footballmatch',
            name='stadium',
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='match_details',
            field=models.JSONField(null=True),
        ),
    ]
