# Generated by Django 3.2.11 on 2022-06-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0009_auto_20220621_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballteam',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='footballteam',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='footballteam',
            name='land',
        ),
        migrations.RemoveField(
            model_name='footballteam',
            name='lat_lan',
        ),
        migrations.RemoveField(
            model_name='footballteam',
            name='location',
        ),
        migrations.RemoveField(
            model_name='footballteam',
            name='stadium',
        ),
        migrations.AddField(
            model_name='footballteam',
            name='team_info',
            field=models.JSONField(null=True),
        ),
    ]
