# Generated by Django 3.2.11 on 2022-06-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0010_auto_20220622_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballmatch',
            name='odds',
            field=models.TextField(null=True),
        ),
    ]
