# Generated by Django 3.2.11 on 2022-06-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0011_alter_footballmatch_odds'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootballLeague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_league_id', models.CharField(max_length=250, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('league_standing', models.TextField(null=True)),
                ('league_history', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.DateTimeField(null=True)),
            ],
        ),
    ]
