# Generated by Django 3.2.11 on 2022-06-22 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0012_footballleague'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footballleague',
            old_name='match_league_id',
            new_name='league_id',
        ),
    ]
