# Generated by Django 3.2.11 on 2022-07-01 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0015_auto_20220701_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footballmatch',
            old_name='kampinfo',
            new_name='match_kampinfo',
        ),
        migrations.RenameField(
            model_name='footballmatch',
            old_name='odds',
            new_name='match_odds',
        ),
    ]
