# Generated by Django 3.2.11 on 2022-07-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0020_auto_20220723_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballteam',
            name='players',
            field=models.JSONField(null=True),
        ),
    ]
