# Generated by Django 3.2.11 on 2022-08-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0021_footballteam_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballleague',
            name='league_history',
        ),
        migrations.AddField(
            model_name='footballleague',
            name='recent_matches',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='footballleague',
            name='upcoming_matches',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='footballleague',
            name='league_standing',
            field=models.JSONField(null=True),
        ),
    ]
