# Generated by Django 3.2.11 on 2022-08-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0022_auto_20220811_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballleague',
            name='season',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='footballleague',
            name='league_id',
            field=models.CharField(max_length=250),
        ),
    ]
