# Generated by Django 3.2.11 on 2022-08-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0024_footballleague_league_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballmatch',
            name='league_country',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
